"""empty message

Revision ID: 17a3ac98803e
Revises: 5067b5b9a598
Create Date: 2019-08-25 16:24:53.392052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a3ac98803e'
down_revision = '5067b5b9a598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.add_column('maker', sa.Column('staff', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maker', 'staff')
    op.create_table('staff',
    sa.Column('maker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('`admin` in (0,1)', name='CONSTRAINT_1'),
    sa.ForeignKeyConstraint(['maker_id'], ['maker.id'], name='staff_ibfk_1'),
    sa.PrimaryKeyConstraint('maker_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
