"""empty message

Revision ID: 2708ef0e2062
Revises: bca27f853a11
Create Date: 2019-08-24 15:31:51.945494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2708ef0e2062'
down_revision = 'bca27f853a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('color_name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'room', ['color_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='unique')
    op.drop_column('room', 'color_name')
    # ### end Alembic commands ###
