"""empty message

Revision ID: 2a7bcda71ae3
Revises: 978d3bcb10b2
Create Date: 2019-08-24 12:35:59.859970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7bcda71ae3'
down_revision = '978d3bcb10b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maker', sa.Column('year', sa.Enum('FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', 'GRADUATE', name='year'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maker', 'year')
    # ### end Alembic commands ###
