"""empty message

Revision ID: 5067b5b9a598
Revises: c8ba0ff09c37
Create Date: 2019-08-25 15:28:48.274227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5067b5b9a598'
down_revision = 'c8ba0ff09c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('usable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'usable')
    # ### end Alembic commands ###
