"""empty message

Revision ID: 7a3243f06fae
Revises: 
Create Date: 2019-08-04 19:59:58.462544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3243f06fae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('rfid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('staff',
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['maker_id'], ['maker.id'], ),
    sa.PrimaryKeyConstraint('maker_id')
    )
    op.create_table('visit',
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=False),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maker_id'], ['maker.id'], ),
    sa.PrimaryKeyConstraint('maker_id', 'in_time')
    )
    op.create_table('training',
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['maker.id'], ),
    sa.PrimaryKeyConstraint('maker_id', 'equipment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    op.drop_table('visit')
    op.drop_table('staff')
    op.drop_table('equipment')
    op.drop_table('room')
    op.drop_table('maker')
    # ### end Alembic commands ###
