"""empty message

Revision ID: 7c167e23c238
Revises: 
Create Date: 2019-08-07 20:44:16.567864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c167e23c238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maker', 'classification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maker', sa.Column('classification', mysql.ENUM('STUDENT', 'FACULTY', 'STAFF', 'RESEARCHER'), nullable=False))
    # ### end Alembic commands ###
