"""empty message

Revision ID: 7ef0a53b0b25
Revises: 5b2b22587ebd
Create Date: 2019-09-02 16:45:44.561214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef0a53b0b25'
down_revision = '5b2b22587ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'training_type', ['color_id'])
    op.create_unique_constraint(None, 'training_type', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_type', type_='unique')
    op.drop_constraint(None, 'training_type', type_='unique')
    # ### end Alembic commands ###
