"""empty message

Revision ID: 978d3bcb10b2
Revises: 7c167e23c238
Create Date: 2019-08-07 20:53:06.265690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978d3bcb10b2'
down_revision = '7c167e23c238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maker', sa.Column('classification', sa.Enum('STUDENT', 'FACULTY', 'STAFF', 'RESEARCHER', name='classification'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maker', 'classification')
    # ### end Alembic commands ###
