"""empty message

Revision ID: 981d4b1c1572
Revises: 2708ef0e2062
Create Date: 2019-08-25 15:13:02.715110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981d4b1c1572'
down_revision = '2708ef0e2062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit', sa.Column('purpose', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visit', 'equipment', ['purpose'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_column('visit', 'purpose')
    # ### end Alembic commands ###
