"""empty message

Revision ID: da1867f4e757
Revises: de1207755ab7
Create Date: 2019-08-05 12:18:56.727570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da1867f4e757'
down_revision = 'de1207755ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='room')
    op.drop_column('room', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('name', 'room', ['name'], unique=True)
    # ### end Alembic commands ###
