"""empty message

Revision ID: de1207755ab7
Revises: 7a3243f06fae
Create Date: 2019-08-04 21:23:46.611204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1207755ab7'
down_revision = '7a3243f06fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'room', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='unique')
    op.drop_column('room', 'name')
    # ### end Alembic commands ###
